version: '3.9'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: "redis:alpine"

# version: '2'
# services:
#     web:
#         build: .
#         ports:
#             - "5000:5000"
#         volumes:
#             - .:/code
#         depends_on:
#             - redis
#     redis:
#         image: redis
